# Generated by Django 6.0.5 on 2026-05-25 02:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('conversations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CRMLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('webhook_url', models.URLField()),
                ('status', models.CharField(choices=[('success', 'Success'), ('failed', 'Failed'), ('pending', 'Pending')], default='pending', max_length=20)),
                ('response_code', models.IntegerField(blank=True, null=True)),
                ('attempt_count', models.IntegerField(default=0)),
                ('last_attempt_at', models.DateTimeField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('response', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='crm_log', to='conversations.response')),
            ],
            options={
                'verbose_name': 'CRM Log',
                'verbose_name_plural': 'CRM Logs',
                'db_table': 'crm_log',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='GeminiLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_tokens', models.IntegerField(default=0)),
                ('response_tokens', models.IntegerField(default=0)),
                ('total_tokens', models.IntegerField(default=0)),
                ('model', models.CharField(default='gemini-pro', max_length=100)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('conversation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gemini_logs', to='conversations.conversation')),
            ],
            options={
                'verbose_name': 'Gemini Log',
                'verbose_name_plural': 'Gemini Logs',
                'db_table': 'gemini_log',
                'ordering': ['-timestamp'],
            },
        ),
    ]
