# Generated by Django 6.0.5 on 2026-05-25 02:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('conversations', '0003_initial'),
        ('moderation', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='moderationlog',
            name='moderator',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='moderation_logs', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='moderationlog',
            name='response',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='moderation_logs', to='conversations.response'),
        ),
        migrations.AddField(
            model_name='moderationqueue',
            name='assigned_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_moderations', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='moderationqueue',
            name='response',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='moderation_queue', to='conversations.response'),
        ),
        migrations.AddIndex(
            model_name='moderationlog',
            index=models.Index(fields=['moderator', '-timestamp'], name='moderation__moderat_2d030f_idx'),
        ),
        migrations.AddIndex(
            model_name='moderationlog',
            index=models.Index(fields=['response'], name='moderation__respons_158c14_idx'),
        ),
        migrations.AddIndex(
            model_name='moderationqueue',
            index=models.Index(fields=['status', '-created_at'], name='moderation__status_30d459_idx'),
        ),
    ]
